version: "3.1"

services:
  tgbot:
    env_file:
      - ".env"
    container_name: $APP_NAME
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    restart: always
    networks:
      - botnet
    volumes:
      - .:/src


networks:
  botnet:
    driver: bridge